# Generated by Django 3.1.1 on 2020-09-24 06:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='noname', max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_firstname', message='First name must be Alphanumeric', regex='^[a-z A-Z]*$')])),
                ('Last_Name', models.CharField(default='noname', max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_lastname', message='Last name must be Alphanumeric', regex='^[a-z A-Z]*$')])),
                ('Username', models.CharField(default='noname', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Username must be valid', regex='^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$')])),
                ('Password', models.CharField(max_length=256)),
                ('Role', models.CharField(default='user', max_length=256)),
                ('Status', models.BooleanField(default=False)),
                ('Is_Email_Verified', models.BooleanField(default=False)),
                ('Gender', models.CharField(default='male', max_length=256)),
                ('Streams', models.IntegerField(default=0)),
                ('UsedStreams', models.IntegerField(default=0)),
                ('image', models.ImageField(default='/static/images/dummy.png', upload_to='images/%y/%m/%d/%H/%m/%S/')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='null')),
                ('FileHash', models.TextField(default='null')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_user', to='musicapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='null')),
                ('Date', models.DateField(blank=True, default=datetime.date(2020, 9, 23), null=True)),
                ('Time', models.DateTimeField(blank=True, default=datetime.time(23, 25, 42, 719551), null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_report1_user', to='musicapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.IntegerField(default=0)),
                ('Hash', models.TextField(default='null')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsciber_user', to='musicapp.songs')),
            ],
        ),
    ]
