# Generated by Django 3.1.1 on 2020-09-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
